name: Release Drafter

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    draft:
        name: Release Draft
        runs-on: ubuntu-latest
        
        outputs:
            tag_name: ${{ steps.drafter.outputs.tag_name }}
        
        steps:
            -   id: drafter
                uses: release-drafter/release-drafter@v6
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
