name: Tests

on:
    push:
    pull_request:

permissions: read-all

jobs:
    coverage:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Types tests
                run: php vendor/bin/pest --coverage

    unit:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.2, 8.3, 8.4 ]

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Unit tests
                run: php vendor/bin/pest --compact
